apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: {{ .Values.spark.worker.replicas }}
  selector:
    matchLabels:
      app: spark
      role: worker
  template:
    metadata:
      labels:
        app: spark
        role: worker
    spec:
      containers:
        - name: spark-worker
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: {{ toJson .Values.spark.worker.extraArgs }}
          env: {{ toYaml .Values.spark.worker.env | nindent 12 }}
          ports:
            - containerPort: {{ .Values.spark.worker.webPort }}
